"""Type stub for the CFFI-generated _minidsp_cffi extension module."""

from typing import Any, overload

# ---------------------------------------------------------------------------
# CFFI pointer / buffer types (opaque to the type checker)
# ---------------------------------------------------------------------------

class CData:
    """Opaque CFFI data handle (pointer, array, struct, etc.)."""
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...

# ---------------------------------------------------------------------------
# ffi object — only the methods the Python wrappers actually call
# ---------------------------------------------------------------------------

class _FFI:
    NULL: CData

    def cast(self, cdecl: str, value: Any) -> CData: ...
    def new(self, cdecl: str, init: Any = ...) -> CData: ...
    def string(self, cdata: CData, maxlen: int = ...) -> bytes: ...
    def buffer(self, cdata: CData, size: int = ...) -> Any: ...
    def from_buffer(self, cdecl: str, python_buffer: Any) -> CData: ...
    def gc(self, cdata: CData, destructor: Any) -> CData: ...

ffi: _FFI

# ---------------------------------------------------------------------------
# lib object — C function bindings
# ---------------------------------------------------------------------------

class _Lib:
    # --- Basic signal measurement ---
    def MD_dot(self, a: CData, b: CData, N: int) -> float: ...
    def MD_entropy(self, a: CData, N: int, clip: bool) -> float: ...
    def MD_energy(self, a: CData, N: int) -> float: ...
    def MD_power(self, a: CData, N: int) -> float: ...
    def MD_power_db(self, a: CData, N: int) -> float: ...

    # --- Signal analysis ---
    def MD_rms(self, a: CData, N: int) -> float: ...
    def MD_zero_crossing_rate(self, a: CData, N: int) -> float: ...
    def MD_autocorrelation(self, a: CData, N: int, out: CData, max_lag: int) -> None: ...
    def MD_peak_detect(self, a: CData, N: int, threshold: float, min_distance: int, peaks_out: CData, num_peaks_out: CData) -> None: ...
    def MD_f0_autocorrelation(self, signal: CData, N: int, sample_rate: float, min_freq_hz: float, max_freq_hz: float) -> float: ...
    def MD_f0_fft(self, signal: CData, N: int, sample_rate: float, min_freq_hz: float, max_freq_hz: float) -> float: ...
    def MD_mix(self, a: CData, b: CData, out: CData, N: int, w_a: float, w_b: float) -> None: ...

    # --- Simple effects ---
    def MD_delay_echo(self, inp: CData, out: CData, N: int, delay_samples: int, feedback: float, dry: float, wet: float) -> None: ...
    def MD_tremolo(self, inp: CData, out: CData, N: int, rate_hz: float, depth: float, sample_rate: float) -> None: ...
    def MD_comb_reverb(self, inp: CData, out: CData, N: int, delay_samples: int, feedback: float, dry: float, wet: float) -> None: ...

    # --- FIR filters / convolution ---
    def MD_convolution_num_samples(self, signal_len: int, kernel_len: int) -> int: ...
    def MD_convolution_time(self, signal: CData, signal_len: int, kernel: CData, kernel_len: int, out: CData) -> None: ...
    def MD_moving_average(self, signal: CData, signal_len: int, window_len: int, out: CData) -> None: ...
    def MD_fir_filter(self, signal: CData, signal_len: int, coeffs: CData, num_taps: int, out: CData) -> None: ...
    def MD_design_lowpass_fir(self, coeffs: CData, num_taps: int, cutoff_freq: float, sample_rate: float, kaiser_beta: float) -> None: ...
    def MD_convolution_fft_ola(self, signal: CData, signal_len: int, kernel: CData, kernel_len: int, out: CData) -> None: ...

    # --- Signal scaling ---
    def MD_scale(self, inp: float, oldmin: float, oldmax: float, newmin: float, newmax: float) -> float: ...
    def MD_scale_vec(self, inp: CData, out: CData, N: int, oldmin: float, oldmax: float, newmin: float, newmax: float) -> None: ...
    def MD_fit_within_range(self, inp: CData, out: CData, N: int, newmin: float, newmax: float) -> None: ...
    def MD_adjust_dblevel(self, inp: CData, out: CData, N: int, dblevel: float) -> None: ...

    # --- FFT / Spectrum analysis ---
    def MD_lowpass_brickwall(self, signal: CData, length: int, cutoff_hz: float, sample_rate: float) -> None: ...
    def MD_magnitude_spectrum(self, signal: CData, N: int, mag_out: CData) -> None: ...
    def MD_power_spectral_density(self, signal: CData, N: int, psd_out: CData) -> None: ...
    def MD_phase_spectrum(self, signal: CData, N: int, phase_out: CData) -> None: ...
    def MD_stft_num_frames(self, signal_len: int, N: int, hop: int) -> int: ...
    def MD_stft(self, signal: CData, signal_len: int, N: int, hop: int, mag_out: CData) -> None: ...
    def MD_mel_filterbank(self, N: int, sample_rate: float, num_mels: int, min_freq_hz: float, max_freq_hz: float, filterbank_out: CData) -> None: ...
    def MD_mel_energies(self, signal: CData, N: int, sample_rate: float, num_mels: int, min_freq_hz: float, max_freq_hz: float, mel_out: CData) -> None: ...
    def MD_mfcc(self, signal: CData, N: int, sample_rate: float, num_mels: int, num_coeffs: int, min_freq_hz: float, max_freq_hz: float, mfcc_out: CData) -> None: ...

    # --- Math utilities ---
    def MD_bessel_i0(self, x: float) -> float: ...
    def MD_sinc(self, x: float) -> float: ...

    # --- Window generation ---
    def MD_Gen_Hann_Win(self, out: CData, n: int) -> None: ...
    def MD_Gen_Hamming_Win(self, out: CData, n: int) -> None: ...
    def MD_Gen_Blackman_Win(self, out: CData, n: int) -> None: ...
    def MD_Gen_Rect_Win(self, out: CData, n: int) -> None: ...
    def MD_Gen_Kaiser_Win(self, out: CData, n: int, beta: float) -> None: ...

    # --- Signal generators ---
    def MD_sine_wave(self, output: CData, N: int, amplitude: float, freq: float, sample_rate: float) -> None: ...
    def MD_white_noise(self, output: CData, N: int, amplitude: float, seed: int) -> None: ...
    def MD_impulse(self, output: CData, N: int, amplitude: float, position: int) -> None: ...
    def MD_chirp_linear(self, output: CData, N: int, amplitude: float, f_start: float, f_end: float, sample_rate: float) -> None: ...
    def MD_chirp_log(self, output: CData, N: int, amplitude: float, f_start: float, f_end: float, sample_rate: float) -> None: ...
    def MD_square_wave(self, output: CData, N: int, amplitude: float, freq: float, sample_rate: float) -> None: ...
    def MD_sawtooth_wave(self, output: CData, N: int, amplitude: float, freq: float, sample_rate: float) -> None: ...
    def MD_shepard_tone(self, output: CData, N: int, amplitude: float, base_freq: float, sample_rate: float, rate_octaves_per_sec: float, num_octaves: int) -> None: ...

    # --- DTMF ---
    def MD_dtmf_signal_length(self, num_digits: int, sample_rate: float, tone_ms: int, pause_ms: int) -> int: ...
    def MD_dtmf_generate(self, output: CData, digits: bytes, sample_rate: float, tone_ms: int, pause_ms: int) -> None: ...
    def MD_dtmf_detect(self, signal: CData, signal_len: int, sample_rate: float, tones_out: CData, max_tones: int) -> int: ...

    # --- Resource cleanup ---
    def MD_shutdown(self) -> None: ...

    # --- GCC delay estimation ---
    def MD_get_delay(self, siga: CData, sigb: CData, N: int, ent: CData, margin: int, weightfunc: int) -> int: ...
    def MD_get_multiple_delays(self, sigs: CData, M: int, N: int, margin: int, weightfunc: int, outdelays: CData) -> None: ...
    def MD_gcc(self, siga: CData, sigb: CData, N: int, lagvals: CData, weightfunc: int) -> None: ...

    # --- Spectrogram text ---
    def MD_spectrogram_text(self, output: CData, max_len: int, text: bytes, freq_lo: float, freq_hi: float, duration_sec: float, sample_rate: float) -> int: ...

    # --- Resampling ---
    def MD_resample_output_len(self, input_len: int, in_rate: float, out_rate: float) -> int: ...
    def MD_resample(self, inp: CData, input_len: int, output: CData, max_output_len: int, in_rate: float, out_rate: float, num_zero_crossings: int, kaiser_beta: float) -> int: ...

    # --- Steganography ---
    def MD_steg_capacity(self, signal_len: int, sample_rate: float, method: int) -> int: ...
    def MD_steg_encode(self, host: CData, output: CData, signal_len: int, sample_rate: float, message: bytes, method: int) -> int: ...
    def MD_steg_decode(self, stego: CData, signal_len: int, sample_rate: float, message_out: CData, max_msg_len: int, method: int) -> int: ...
    def MD_steg_encode_bytes(self, host: CData, output: CData, signal_len: int, sample_rate: float, data: CData, data_len: int, method: int) -> int: ...
    def MD_steg_decode_bytes(self, stego: CData, signal_len: int, sample_rate: float, data_out: CData, max_len: int, method: int) -> int: ...
    def MD_steg_detect(self, signal: CData, signal_len: int, sample_rate: float, payload_type_out: CData) -> int: ...

    # --- Biquad ---
    def BiQuad(self, sample: float, b: CData) -> float: ...
    def BiQuad_new(self, type: int, dbGain: float, freq: float, srate: float, bandwidth: float) -> CData: ...
    def free(self, ptr: CData) -> None: ...

lib: _Lib
